<img src="https://github.com/zece05/DSB-Unit-02/blob/main/02%20-%20Exploring%20and%20Joining/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Lab: Cleaning Rock Song Data
---

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

%matplotlib inline

### 1. Load `rock.csv` and do an initial examination of its data columns.

In [10]:
rockfile = "https://raw.githubusercontent.com/zece05/DSB-Unit-02/refs/heads/main/02%20-%20Exploring%20and%20Joining/practice/data/rock.csv"

In [11]:
# Load the data.

rock = pd.read_csv(rockfile)

In [12]:
# Look at the information regarding its columns.
rock.columns

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

In [13]:
rock['Year?'].value_counts()

Year?
1    1653
0     577
Name: count, dtype: int64

### 2.  Clean up the column names.

Let's clean up the column names. There are two ways we can accomplish this:

#### 2.A Change the column names when you import the data using `pd.read_csv()`.

Notice that, when passing `names=[..A LIST OF STRING..]` with a number of columns that matches the number of strings in the passed list, you replace the column names.

NOTE: When you create custom column names, the first row of the `.csv` already represents a header. It is important to tell `pandas` to skip that row. The `skiprows=1` keyword argument to `read_csv()` will tell `pandas` to skip the first row.

In [14]:
# Change the column names when loading the '.csv':
cols = ['Song', 'Artist', 'Release_Year', 'Song_Artist', 'First',
       'Year', 'PlayCount', 'Year_Playcount']
rock = pd.read_csv(rockfile, names=cols, skiprows=1)

rock.head()

,Song,Artist,Release_Year,Song_Artist,First,Year,PlayCount,Year_Playcount
0,Caught Up in You,.38 Special,1982,Caught Up in You by .38 Special,1,1,82,82
1,Fantasy Girl,.38 Special,NaN,Fantasy Girl by .38 Special,1,0,3,0
2,Hold On Loosely,.38 Special,1981,Hold On Loosely by .38 Special,1,1,85,85
3,Rockin' Into the Night,.38 Special,1980,Rockin' Into the Night by .38 Special,1,1,18,18
4,Art For Arts Sake,10cc,1975,Art For Arts Sake by 10cc,1,1,1,1

#### 2.B Change column names using the `.rename()` function.

The `.rename()` function takes an argument, `columns=name_dict`, in which `name_dict` is a dictionary containing the original column names as keys and the new column names as values.

In [15]:
# Change the column names using the `.rename()` function.

rock.rename(columns = {'Song':'song','Artist':'artist', 'Release_Year':'release_year', 'Song_Artist':'song_artist',
                       'First':'first', 'Year':'year', 'PlayCount':'playcount', 'Year_Playcount': 'year_playcount'},
            inplace=True)

rock.head()

,song,artist,release_year,song_artist,first,year,playcount,year_playcount
0,Caught Up in You,.38 Special,1982,Caught Up in You by .38 Special,1,1,82,82
1,Fantasy Girl,.38 Special,NaN,Fantasy Girl by .38 Special,1,0,3,0
2,Hold On Loosely,.38 Special,1981,Hold On Loosely by .38 Special,1,1,85,85
3,Rockin' Into the Night,.38 Special,1980,Rockin' Into the Night by .38 Special,1,1,18,18
4,Art For Arts Sake,10cc,1975,Art For Arts Sake by 10cc,1,1,1,1

#### 2.C Reassigning the `.columns` attribute of a DataFrame.

You can also just reassign the `.columns` attribute to a list of strings containing the new column names.

The only caveat with reassigning `.columns` is that you have to reassign all of the column names at once. You can't partially replace a value by working on `.columns` directly. You have to reassign `.columns` with a list of equal length.

In [18]:
# Replace the column names by reassigning the `.columns` attribute.

rock.columns = ['pesma', 'umetnik', 'release_year', 'song_artist', 'first', 'year',
       'playcount', 'year_playcount']

In [19]:

rock.head()

,pesma,umetnik,release_year,song_artist,first,year,playcount,year_playcount
0,Caught Up in You,.38 Special,1982,Caught Up in You by .38 Special,1,1,82,82
1,Fantasy Girl,.38 Special,NaN,Fantasy Girl by .38 Special,1,0,3,0
2,Hold On Loosely,.38 Special,1981,Hold On Loosely by .38 Special,1,1,85,85
3,Rockin' Into the Night,.38 Special,1980,Rockin' Into the Night by .38 Special,1,1,18,18
4,Art For Arts Sake,10cc,1975,Art For Arts Sake by 10cc,1,1,1,1

### 3. Subsetting data where null values exist.

We have mixed `str` and `NaN` values in the `release` column. `NaN` stands for "not a number" and is the way `pandas` handles "nulls" or nonexistent data. We can use the `.isnull()` method of a Series to find null values.

Print the header of the data subset to where the `release` column is null values.

In [23]:
# Show records where df['release'] is null
rock[rock['release_year'].isnull()].head()

,pesma,umetnik,release_year,song_artist,first,year,playcount,year_playcount
1,Fantasy Girl,.38 Special,NaN,Fantasy Girl by .38 Special,1,0,3,0
10,"Baby, Please Don't Go",AC/DC,NaN,"Baby, Please Don't Go by AC/DC",1,0,1,0
13,CAN'T STOP ROCK'N'ROLL,AC/DC,NaN,CAN'T STOP ROCK'N'ROLL by AC/DC,1,0,5,0
16,Girls Got Rhythm,AC/DC,NaN,Girls Got Rhythm by AC/DC,1,0,24,0
24,Let's Get It Up,AC/DC,NaN,Let's Get It Up by AC/DC,1,0,4,0

### 4. Update slices of your DataFrame based on mask selection/slices.

In many scenarios, we want to upate values in our DataFrame according to criteria. Let's say we wanted to set all of the null values in `release` to 0.

With newer versions of `pandas`, in order to manipulate data in the original DataFrame, we have to use `.loc` while performing reassignment using a mask and an index.

For example, the following won't always work:
```python
df[row_mask]['column_name'] = new_value
```

The best way to accomplish the same task is:
```python
df.loc[row_mask, 'column_name'] = new_value
```

For multiple column assignment, you would use:
```python
df.loc[row_mask, ['col_1', 'col_2', 'col_3']] = new_value
```

#### 4.A Let's try it out. Make all of the null values in `release` 0.

In [24]:
# Replace release nulls with 0
rock.loc[rock['release_year'].isna(), 'release_year']=0

#### 4.B Verify that `release` contains no null values.

In [25]:
# A:
rock[rock['release_year'].isnull()].head()

Empty DataFrame
Columns: [pesma, umetnik, release_year, song_artist, first, year, playcount, year_playcount]
Index: []

### 5. Ensure that the data types of the columns make sense.

Verifying column data types is a critical part of data munging. If columns have the wrong data type, then there is usually corrupted or incorrect data in some of the observations.

#### 5.A Look at the data types for the columns. Are any incorrect given what the data represents?

In [26]:
# A:
rock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2230 entries, 0 to 2229
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pesma           2230 non-null   object
 1   umetnik         2230 non-null   object
 2   release_year    2230 non-null   object
 3   song_artist     2230 non-null   object
 4   first           2230 non-null   int64
 5   year            2230 non-null   int64
 6   playcount       2230 non-null   int64
 7   year_playcount  2230 non-null   int64
dtypes: int64(4), object(4)
memory usage: 139.5+ KB

### 6. Investigate and clean up the `release` column.

The `release` column is a string data type when it should be an integer.

#### 6.A Figure out what value(s) are causing the `release` column to be encoded as a string instead of an integer.

In [ ]:
'SONGFACTS.COM'

In [40]:

rock['release_year'].unique()

array(['1982', 0, '1981', '1980', '1975', '2000', '2002', '1992', '1985',
       '1993', '1976', '1995', '1979', '1984', '1977', '1990', '1986',
       '1974', '2014', '1987', '1973', '2001', '1989', '1997', '1971',
       '1972', '1994', '1970', '1966', '1965', '1983', '1955', '1978',
       '1969', '1999', '1968', '1988', '1962', '2007', '1967', '1958',
       '1071', '1996', '1991', '2005', '2011', '2004', '2012', '2003',
       '1998', '2008', '1964', '2013', '2006', 'SONGFACTS.COM', '1963',
       '1961'], dtype=object)

,pesma,umetnik,release_year,song_artist,first,year,playcount,year_playcount
1504,Bullfrog Blues,Rory Gallagher,SONGFACTS.COM,Bullfrog Blues by Rory Gallagher,1,1,1,1

In [39]:
# A:

str

#### 6.B Look at the rows in which there is incorrect data in the `release` column.

In [65]:
# A:
rock[rock['release_year']=='SONGFACTS.COM']

Empty DataFrame
Columns: [pesma, umetnik, release_year, song_artist, first, year, playcount, year_playcount]
Index: []

#### 6.C. Clean up the data. Normally we may replace the offending data with null np.nan values, however we previously converted all of the nan values in the release column to zeros so we might as well continue with the same practice. Replacing with 0 (or nan) will allow us to convert the column to numeric.

In [42]:
# A:
rock['release_year'] = pd.to_numeric(rock['release_year'], errors='coerce').fillna(0).astype(int)

### 7. Get summary statistics for the `release` column using the `.describe()` function.

Now that the `release` column is finally a numeric data type, we can apply the `.describe()` function.  

#### 7.A Print out the summary stats for the `release` column. What is the earliest and latest release date?

In [43]:
# A:
rock['release_year'].describe()

count    2230.000000
mean     1465.331390
std       867.196161
min         0.000000
25%         0.000000
50%      1973.000000
75%      1981.000000
max      2014.000000
Name: release_year, dtype: float64

#### 7.B Based on the summary statistics, is there anything else wrong with the `release` column?

In [47]:
# A:
#Yes, min and 25% are 0
# Year 1071

[]

_Looking at the DataFrame that contains the year 1071, we can see that the year was probably corrupted and should be replaced with something else if possible._

### *Stretch: we have not yet covered `.apply()`.  See if you can work out this part.*

### 8. Make changes and investigate using custom functions with `.apply()`.

Let's say we want to traverse every single row in our data set and apply a function to that row.

#### 8.A Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970.

In [55]:
rock.columns

Index(['pesma', 'umetnik', 'release_year', 'song_artist', 'first', 'year',
       'playcount', 'year_playcount'],
      dtype='object')

In [56]:
 rock[['pesma', 'umetnik', 'release_year']][rock['release_year']<1970]

                         pesma      umetnik  release_year
1                 Fantasy Girl  .38 Special             0
10       Baby, Please Don't Go        AC/DC             0
13      CAN'T STOP ROCK'N'ROLL        AC/DC             0
16            Girls Got Rhythm        AC/DC             0
24             Let's Get It Up        AC/DC             0
...                        ...          ...           ...
2216   I'm Bad, I'm Nationwide       ZZ Top             0
2218             Just Got Paid       ZZ Top             0
2221  My Head's In Mississippi       ZZ Top             0
2222        Party On The Patio       ZZ Top             0
2225   She Loves My Automobile       ZZ Top             0

[845 rows x 3 columns]

In [75]:
# A:
def applyinaction(df):
  return df[['pesma', 'umetnik', 'release_year']][df['release_year']<1970]

#rock[['pesma', 'umetnik', 'release_year']].apply(applyinaction)
applyinaction(rock)

                         pesma      umetnik  release_year
1                 Fantasy Girl  .38 Special             0
10       Baby, Please Don't Go        AC/DC             0
13      CAN'T STOP ROCK'N'ROLL        AC/DC             0
16            Girls Got Rhythm        AC/DC             0
24             Let's Get It Up        AC/DC             0
...                        ...          ...           ...
2216   I'm Bad, I'm Nationwide       ZZ Top             0
2218             Just Got Paid       ZZ Top             0
2221  My Head's In Mississippi       ZZ Top             0
2222        Party On The Patio       ZZ Top             0
2225   She Loves My Automobile       ZZ Top             0

[845 rows x 3 columns]

#### 8.B Using the `.apply()` function, apply the function you wrote to the first four rows of the DataFrame.

You will need to tell the `apply` function to operate row by row. Setting the keyword argument as `axis=1` indicates that the function should be applied to each row individually.

In [66]:
# A:
def prikazi_info_o_pesmi(row):
    pesma = row['pesma']
    izvodjac = row['umetnik']
    pre_1970 = row['release_year'] < 1970

    print(f'Pesma: {pesma}, Izvođač: {izvodjac}, Izdato pre 1970: {pre_1970}')
    return None

# Primena na svaki red u DataFrame-u:
answr = rock.apply(prikazi_info_o_pesmi, axis=1)
answr

Pesma: Caught Up in You, Izvođač: .38 Special, Izdato pre 1970: False
Pesma: Fantasy Girl, Izvođač: .38 Special, Izdato pre 1970: True
Pesma: Hold On Loosely, Izvođač: .38 Special, Izdato pre 1970: False
Pesma: Rockin' Into the Night, Izvođač: .38 Special, Izdato pre 1970: False
Pesma: Art For Arts Sake, Izvođač: 10cc, Izdato pre 1970: False
Pesma: Kryptonite, Izvođač: 3 Doors Down, Izdato pre 1970: False
Pesma: Loser, Izvođač: 3 Doors Down, Izdato pre 1970: False
Pesma: When I'm Gone, Izvođač: 3 Doors Down, Izdato pre 1970: False
Pesma: What's Up?, Izvođač: 4 Non Blondes, Izdato pre 1970: False
Pesma: Take On Me, Izvođač: a-ha, Izdato pre 1970: False
Pesma: Baby, Please Don't Go, Izvođač: AC/DC, Izdato pre 1970: True
Pesma: Back In Black, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Big Gun, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: CAN'T STOP ROCK'N'ROLL, Izvođač: AC/DC, Izdato pre 1970: True
Pesma: Dirty Deeds Done Dirt Cheap, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: For Those About To Rock, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Girls Got Rhythm, Izvođač: AC/DC, Izdato pre 1970: True
Pesma: Hard As A Rock, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Have a Drink On Me, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Hells Bells, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Highway To Hell, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: It's A Long Way To The Top, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Jailbreak, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Let There Be Rock, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Let's Get It Up, Izvođač: AC/DC, Izdato pre 1970: True
Pesma: Live Wire, Izvođač: AC/DC, Izdato pre 1970: True
Pesma: Moneytalks, Izvođač: AC/DC, Izdato pre 1970: True
Pesma: Night Prowler, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Rock and Roll Ain't Noise Pollution, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Shoot To Thrill, Izvođač: AC/DC, Izdato pre 1970: True
Pesma: Shot Down In Flames, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Sin City, Izvođač: AC/DC, Izdato pre 1970: True
Pesma: T.N.T., Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Thunderstruck, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Touch Too Much, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: What Do You Do For Money Honey, Izvođač: AC/DC, Izdato pre 1970: True
Pesma: Who Made Who, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: Whole Lotta Rosie, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: You Shook Me All Night Long, Izvođač: AC/DC, Izdato pre 1970: False
Pesma: How Long, Izvođač: Ace, Izdato pre 1970: False
Pesma: Dog On A Leash, Izvođač: Adelitas Way, Izdato pre 1970: False
Pesma: Angel, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Baby, Please Don't Go, Izvođač: Aerosmith, Izdato pre 1970: True
Pesma: Back in the Saddle, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Big Ten Inch, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Come Together, Izvođač: Aerosmith, Izdato pre 1970: True
Pesma: Crazy, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Cryin', Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Draw The Line, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Dream On, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Dude (Looks Like a Lady), Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Jaded, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Janie's Got A Gun, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Kings and Queens, Izvođač: Aerosmith, Izdato pre 1970: True
Pesma: Last Child, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Let the Music Do the Talking, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Livin' On The Edge, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Love In An Elevator, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Mama Kin, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: No More No More, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: One Way Street, Izvođač: Aerosmith, Izdato pre 1970: True
Pesma: Pink, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Rag Doll, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Same Old Song and Dance, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Seasons of Wither, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Sweet Emotion, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: The Other Side, Izvođač: Aerosmith, Izdato pre 1970: True
Pesma: Toys in the Attic, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Train Kept A-Rollin', Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: Walk This Way, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: What It Takes, Izvođač: Aerosmith, Izdato pre 1970: False
Pesma: You See Me Crying, Izvođač: Aerosmith, Izdato pre 1970: True
Pesma: Hand In My Pocket, Izvođač: Alanis Morissette, Izdato pre 1970: False
Pesma: You Oughta Know, Izvođač: Alanis Morissette, Izdato pre 1970: False
Pesma: Black Velvet, Izvođač: Alannah Myles, Izdato pre 1970: False
Pesma: Fantasy, Izvođač: Aldo Nova, Izdato pre 1970: True
Pesma: BE MY LOVER, Izvođač: Alice Cooper, Izdato pre 1970: True
Pesma: Billion Dollar Babies, Izvođač: Alice Cooper, Izdato pre 1970: False
Pesma: Eighteen, Izvođač: Alice Cooper, Izdato pre 1970: False
Pesma: Elected, Izvođač: Alice Cooper, Izdato pre 1970: False
Pesma: House Of Fire, Izvođač: Alice Cooper, Izdato pre 1970: True
Pesma: I'm Eighteen, Izvođač: Alice Cooper, Izdato pre 1970: False
Pesma: No More Mr. Nice Guy, Izvođač: Alice Cooper, Izdato pre 1970: False
Pesma: School's Out, Izvođač: Alice Cooper, Izdato pre 1970: False
Pesma: Under My Wheels, Izvođač: Alice Cooper, Izdato pre 1970: False
Pesma: Welcome To My Nightmare, Izvođač: Alice Cooper, Izdato pre 1970: False
Pesma: Down in a Hole, Izvođač: Alice In Chains, Izdato pre 1970: False
Pesma: Man In The Box, Izvođač: Alice In Chains, Izdato pre 1970: False
Pesma: No Excuses, Izvođač: Alice In Chains, Izdato pre 1970: False
Pesma: Rooster, Izvođač: Alice In Chains, Izdato pre 1970: False
Pesma: Them Bones, Izvođač: Alice In Chains, Izdato pre 1970: False
Pesma: Would?, Izvođač: Alice In Chains, Izdato pre 1970: False
Pesma: Ain't Wastin' Time No More, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: Blue Sky, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: Good Clean Fun, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: In Memory Of Elizabeth Reed, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: Jessica, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: Melissa, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: Midnight Rider, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: No One to Run With, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: One Way Out, Izvođač: Allman Brothers Band, Izdato pre 1970: True
Pesma: Ramblin' Man, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: Southbound, Izvođač: Allman Brothers Band, Izdato pre 1970: True
Pesma: Statesboro Blues, Izvođač: Allman Brothers Band, Izdato pre 1970: False
Pesma: Whippin' Post, Izvođač: Allman Brothers Band, Izdato pre 1970: True
Pesma: A Horse With No Name, Izvođač: America, Izdato pre 1970: False
Pesma: Sister Golden Hair, Izvođač: America, Izdato pre 1970: False
Pesma: Ventura Highway, Izvođač: America, Izdato pre 1970: False
Pesma: Don't Bring Me Down, Izvođač: Animals II, Izdato pre 1970: True
Pesma: Don't Let Me Be Misunderstood, Izvođač: Animals II, Izdato pre 1970: True
Pesma: Immigrant Song, Izvođač: Ann Wilson, Izdato pre 1970: True
Pesma: Roller, Izvođač: April Wine, Izdato pre 1970: True
Pesma: Hold Your Head Up, Izvođač: Argent, Izdato pre 1970: False
Pesma: Coming into Los Angeles, Izvođač: Arlo Guthrie, Izdato pre 1970: True
Pesma: Wayside, Izvođač: Artful Dodger, Izdato pre 1970: True
Pesma: Heat of the Moment, Izvođač: Asia, Izdato pre 1970: False
Pesma: Only Time Will Tell, Izvođač: Asia, Izdato pre 1970: False
Pesma: So Into You, Izvođač: Atlanta Rhythm Section, Izdato pre 1970: False
Pesma: Spooky, Izvođač: Atlanta Rhythm Section, Izdato pre 1970: True
Pesma: Like a Stone, Izvođač: Audioslave, Izdato pre 1970: False
Pesma: Blondes In Black Cars, Izvođač: Autograph, Izdato pre 1970: True
Pesma: Turn Up the Radio, Izvođač: Autograph, Izdato pre 1970: False
Pesma: Rock And Roll Party In The Streets, Izvođač: Axe, Izdato pre 1970: True
Pesma: Let It Ride, Izvođač: Bachman-Turner Overdrive, Izdato pre 1970: False
Pesma: Roll On Down The Highway, Izvođač: Bachman-Turner Overdrive, Izdato pre 1970: True
Pesma: Takin' Care Of Business, Izvođač: Bachman-Turner Overdrive, Izdato pre 1970: False
Pesma: You Ain't Seen Nothin' Yet, Izvođač: Bachman-Turner Overdrive, Izdato pre 1970: False
Pesma: Bad Company, Izvođač: Bad Company, Izdato pre 1970: False
Pesma: Burnin' Sky, Izvođač: Bad Company, Izdato pre 1970: False
Pesma: Can't Get Enough, Izvođač: Bad Company, Izdato pre 1970: False
Pesma: Feel Like Makin' Love, Izvođač: Bad Company, Izdato pre 1970: True
Pesma: Gone Gone Gone, Izvođač: Bad Company, Izdato pre 1970: True
Pesma: Good Lovin' Gone Bad, Izvođač: Bad Company, Izdato pre 1970: True
Pesma: Movin' On, Izvođač: Bad Company, Izdato pre 1970: True
Pesma: Ready For Love, Izvođač: Bad Company, Izdato pre 1970: True
Pesma: Rock 'n' Roll Fantasy, Izvođač: Bad Company, Izdato pre 1970: True
Pesma: Rock Steady, Izvođač: Bad Company, Izdato pre 1970: True
Pesma: Run With The Pack, Izvođač: Bad Company, Izdato pre 1970: True
Pesma: Seagull, Izvođač: Bad Company, Izdato pre 1970: False
Pesma: Shooting Star, Izvođač: Bad Company, Izdato pre 1970: False
Pesma: Silver, Blue And Gold, Izvođač: Bad Company, Izdato pre 1970: True
Pesma: When I See You Smile, Izvođač: Bad English, Izdato pre 1970: False
Pesma: No Matter What, Izvođač: Badfinger, Izdato pre 1970: False
Pesma: Walks Like A Woman, Izvođač: Baton Rouge, Izdato pre 1970: True
Pesma: (You Gotta) Fight for Your Right (To Party), Izvođač: Beastie Boys, Izdato pre 1970: False
Pesma: No Sleep Till Brooklyn, Izvođač: Beastie Boys, Izdato pre 1970: False
Pesma: Loser, Izvođač: Beck, Izdato pre 1970: False
Pesma: In a Big Country, Izvođač: Big Country, Izdato pre 1970: False
Pesma: Rock Around the Clock, Izvođač: Bill Haley, Izdato pre 1970: True
Pesma: AIN'T NO SUNSHINE, Izvođač: Bill Withers, Izdato pre 1970: False
Pesma: Cradle of Love, Izvođač: Billy Idol, Izdato pre 1970: False
Pesma: Dancing With Myself, Izvođač: Billy Idol, Izdato pre 1970: False
Pesma: Eyes Without a Face, Izvođač: Billy Idol, Izdato pre 1970: False
Pesma: Mony Mony, Izvođač: Billy Idol, Izdato pre 1970: True
Pesma: Rebel Yell, Izvođač: Billy Idol, Izdato pre 1970: False
Pesma: White Wedding, Izvođač: Billy Idol, Izdato pre 1970: False
Pesma: Allentown, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Big Shot, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Captain Jack, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Don't Ask Me Why, Izvođač: Billy Joel, Izdato pre 1970: True
Pesma: Goodnight Saigon, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: It's Still Rock And Roll To Me, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Miami 2017 {seen The Lights Go Out On Broadway} (live 1, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Movin' Out (Anthony's Song), Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: My Life, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: New York State Of Mind, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Only The Good Die Young, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Piano Man, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Prelude/angry Young Man, Izvođač: Billy Joel, Izdato pre 1970: True
Pesma: Scenes From An Italian Restaurant, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: SHE'S ALWAYS A WOMAN, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Sometimes A Fantasy, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: The Ballad Of Billy The Kid, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: The Stranger, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: You May Be Right, Izvođač: Billy Joel, Izdato pre 1970: False
Pesma: Baby Come Back, Izvođač: Billy Rankin, Izdato pre 1970: True
Pesma: Everybody Wants You, Izvođač: Billy Squier, Izdato pre 1970: True
Pesma: In the Dark, Izvođač: Billy Squier, Izdato pre 1970: True
Pesma: Lonely Is the Night, Izvođač: Billy Squier, Izdato pre 1970: False
Pesma: My Kinda Lover, Izvođač: Billy Squier, Izdato pre 1970: True
Pesma: Rock Me Tonight, Izvođač: Billy Squier, Izdato pre 1970: False
Pesma: She's a Runner, Izvođač: Billy Squier, Izdato pre 1970: True
Pesma: The Stroke, Izvođač: Billy Squier, Izdato pre 1970: False
Pesma: Children Of The Sun, Izvođač: Billy Thorpe, Izdato pre 1970: True
Pesma: Fairies Wear Boots, Izvođač: Black Sabbath, Izdato pre 1970: False
Pesma: Heaven and Hell, Izvođač: Black Sabbath, Izdato pre 1970: False
Pesma: Iron Man, Izvođač: Black Sabbath, Izdato pre 1970: False
Pesma: N.i.b., Izvođač: Black Sabbath, Izdato pre 1970: False
Pesma: Neon Knights, Izvođač: Black Sabbath, Izdato pre 1970: False
Pesma: Paranoid, Izvođač: Black Sabbath, Izdato pre 1970: False
Pesma: Sweet Leaf, Izvođač: Black Sabbath, Izdato pre 1970: False
Pesma: The Wizard, Izvođač: Black Sabbath, Izdato pre 1970: False
Pesma: War Pigs, Izvođač: Black Sabbath, Izdato pre 1970: False
Pesma: Highway Song, Izvođač: Blackfoot, Izdato pre 1970: True
Pesma: Train, Train, Izvođač: Blackfoot, Izdato pre 1970: False
Pesma: Can't Find My Way Home, Izvođač: Blind Faith, Izdato pre 1970: True
Pesma: Presence of the Lord, Izvođač: Blind Faith, Izdato pre 1970: True
Pesma: No Rain, Izvođač: Blind Melon, Izdato pre 1970: False
Pesma: Presence of the Lord, Izvođač: Blind Melon, Izdato pre 1970: True
Pesma: All the Small Things, Izvođač: Blink-182, Izdato pre 1970: False
Pesma: Call Me, Izvođač: Blondie, Izdato pre 1970: False
Pesma: Heart of Glass, Izvođač: Blondie, Izdato pre 1970: False
Pesma: One Way Or Another, Izvođač: Blondie, Izdato pre 1970: False
Pesma: (Don't Fear) The Reaper, Izvođač: Blue Oyster Cult, Izdato pre 1970: False
Pesma: Bucks Boogie, Izvođač: Blue Oyster Cult, Izdato pre 1970: True
Pesma: Burnin' for You, Izvođač: Blue Oyster Cult, Izdato pre 1970: False
Pesma: Godzilla, Izvođač: Blue Oyster Cult, Izdato pre 1970: False
Pesma: I Love the Night, Izvođač: Blue Oyster Cult, Izdato pre 1970: False
Pesma: Summertime Blues, Izvođač: Blue Oyster Cult, Izdato pre 1970: True
Pesma: Song 2, Izvođač: Blur, Izdato pre 1970: False
Pesma: Just Like A Woman, Izvođač: Bob Dylan, Izdato pre 1970: True
Pesma: Knockin' On Heaven's Door, Izvođač: Bob Dylan, Izdato pre 1970: False
Pesma: Like a Rolling Stone, Izvođač: Bob Dylan, Izdato pre 1970: True
Pesma: Positively 4th Street, Izvođač: Bob Dylan, Izdato pre 1970: True
Pesma: Subterranean Homesick Blues, Izvođač: Bob Dylan, Izdato pre 1970: True
Pesma: Tangled Up In Blue, Izvođač: Bob Dylan, Izdato pre 1970: False
Pesma: Exodus, Izvođač: Bob Marley, Izdato pre 1970: True
Pesma: Jamming, Izvođač: Bob Marley, Izdato pre 1970: True
Pesma: No Woman, No Cry, Izvođač: Bob Marley, Izdato pre 1970: False
Pesma: One Love, Izvođač: Bob Marley, Izdato pre 1970: False
Pesma: Stir It Up, Izvođač: Bob Marley, Izdato pre 1970: True
Pesma: Three Little Birds, Izvođač: Bob Marley, Izdato pre 1970: True
Pesma: Against The Wind, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Betty Lou's Gettin' Out Tonigh, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Come to Poppa, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Feel Like a Number, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Fire Down Below, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Get Out of Denver, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Her Strut, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Hollywood Nights, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Horizontal Bop, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Katmandu, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Mainstreet, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Night Moves, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Old Time Rock & Roll, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Ramblin' Gamblin' Man, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Rock And Roll Never Forgets, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Roll Me Away, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Still the Same, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: Sunspot Baby, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: The Fire Down Below, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Travelin' Man, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Turn On Your Love Light, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Turn The Page, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: We've Got Tonite, Izvođač: Bob Seger, Izdato pre 1970: False
Pesma: You'll Accompany Me, Izvođač: Bob Seger, Izdato pre 1970: True
Pesma: Hypnotized, Izvođač: Bob Welch, Izdato pre 1970: True
Pesma: Bad Medicine, Izvođač: Bon Jovi, Izdato pre 1970: False
Pesma: Blaze of Glory, Izvođač: Bon Jovi, Izdato pre 1970: False
Pesma: Born To Be My Baby, Izvođač: Bon Jovi, Izdato pre 1970: False
Pesma: Lay Your Hands On Me, Izvođač: Bon Jovi, Izdato pre 1970: False
Pesma: Livin' On A Prayer, Izvođač: Bon Jovi, Izdato pre 1970: False
Pesma: Raise Your Hands, Izvođač: Bon Jovi, Izdato pre 1970: True
Pesma: Runaway, Izvođač: Bon Jovi, Izdato pre 1970: False
Pesma: She Don't Know Me, Izvođač: Bon Jovi, Izdato pre 1970: True
Pesma: Wanted Dead or Alive, Izvođač: Bon Jovi, Izdato pre 1970: False
Pesma: You Give Love A Bad Name, Izvođač: Bon Jovi, Izdato pre 1970: False
Pesma: Wait For You, Izvođač: Bonham, Izdato pre 1970: True
Pesma: Green Onions, Izvođač: Booker T. and the MG's, Izdato pre 1970: True
Pesma: A Man I'll Never Be, Izvođač: Boston, Izdato pre 1970: True
Pesma: Amanda, Izvođač: Boston, Izdato pre 1970: False
Pesma: Cool The Engines, Izvođač: Boston, Izdato pre 1970: True
Pesma: Don't Look Back, Izvođač: Boston, Izdato pre 1970: False
Pesma: Feelin' Satisfied, Izvođač: Boston, Izdato pre 1970: True
Pesma: Foreplay (Long Time), Izvođač: Boston, Izdato pre 1970: False
Pesma: Hitch A Ride, Izvođač: Boston, Izdato pre 1970: False
Pesma: Let Me Take You Home Tonight, Izvođač: Boston, Izdato pre 1970: False
Pesma: More Than a Feeling, Izvođač: Boston, Izdato pre 1970: False
Pesma: Party, Izvođač: Boston, Izdato pre 1970: True
Pesma: Peace of Mind, Izvođač: Boston, Izdato pre 1970: False
Pesma: Rock & Roll Band, Izvođač: Boston, Izdato pre 1970: False
Pesma: Smokin', Izvođač: Boston, Izdato pre 1970: False
Pesma: Something About You, Izvođač: Boston, Izdato pre 1970: True
Pesma: The Journey/It's Easy, Izvođač: Boston, Izdato pre 1970: True
Pesma: Used To Bad News, Izvođač: Boston, Izdato pre 1970: True
Pesma: We're Ready, Izvođač: Boston, Izdato pre 1970: True
Pesma: Lido Shuffle, Izvođač: Boz Scaggs, Izdato pre 1970: False
Pesma: Lowdown, Izvođač: Boz Scaggs, Izdato pre 1970: False
Pesma: Tarkio Road, Izvođač: Brewer & Shipley, Izdato pre 1970: True
Pesma: The Way It Is, Izvođač: Bruce Hornsby & The Range, Izdato pre 1970: False
Pesma: Atlantic City, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Backstreets, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Badlands, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Blinded By the Light, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Born In the U.S.A., Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Born To Run, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Cover Me, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Dancing In the Dark, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Glory Days, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Growin' Up, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: Hungry Heart, Izvođač: Bruce Springsteen, Izdato pre 1970: False
Pesma: I'm On Fire, Izvođač: Bruce Springsteen, Izdato pre 1970: False

0       None
1       None
2       None
3       None
4       None
        ...
2225    None
2226    None
2227    None
2228    None
2229    None
Length: 2230, dtype: object

You'll notice that there will be a final output Series of `None` values. The `.apply()` function, if a return value is not specified, will return a Series of `None` values (similar to how the default return for Python functions is `None` when a return statement is not specified).

### 9. Write a function that converts cells in a DataFrame to float and otherwise replaces them with `np.nan`.

If applied to our data, it would keep only the numeric information and otherwise input null values.

Recall that the try-except syntax in Python is a great way to try something and take another action if the initial step fails:

```python
try:
    Perform some action.
except:
   Perform some other action if the first failed with an error.
```

#### 9.A Write the function that takes a column and converts all of its values to float if possible and `np.nan` otherwise. The return value should be the converted Series.

In [ ]:
# A:

#### 9.B Try your function out on the rock song data and ensure the output is what you expected.

In [ ]:
# A:

#### 9.C Describe the new float-only DataFrame.

In [ ]:
# A: